version: '3.8'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    ports:
      - "27017:27017"
    command: mongod --auth --config /etc/mongo/mongodb.conf

volumes:
  mongodb_data:
  mongodb_config: